<?php
$headTitle = 'Ajax';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<hr>
<br>
<div><?= date('H:i:s') ?></div>
<br>
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10 col-11">
        <form id="ajax_user_form">

            <div class="form-group row">
                <label class="control-label col-3" for="firstName">First name:</label>
                <input type="text" class="form-control col-9" id="firstName" name="firstName">
            </div>

            <div class="form-group row">
                <label class="control-label col-3" for="lastName">Last name:</label>
                <input type="text" class="form-control col-9" id="lastName" name="lastName">
            </div>

            <div class="row col-12">
                <div class="offset-3">
                    <button type="submit" class="btn btn-info">Submit</button>
                </div>
            </div>

        </form>
    </div>
</div>
<br>
<h6 id="result"></h6>
