<?= $this->partial('partial/topMenuActive', ['liNum' => (int)0]) ?>

<?php
$headTitle = 'Edit article';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<hr>
<div class="panel">
    <form action="/training/article-edit/12" method="post">
        <input type="text" name="title">
        <input type="submit" value="Submit">
    </form>
</div>
