<?= $this->partial('partial/topMenuActive', ['liNum' => (int)0]) ?>

<?php
$headTitle = 'Article';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<hr>
<?= $this->partial('partial/flash-messenger'); ?>
<div class="panel">
    <a href="/training/article-add" class="btn btn-default">Add article</a>
    <a href="/training/article-edit/12" class="btn btn-default">Edit article</a>
</div>
