<?php ini_set('display_errors', 'On') ?>
<?php error_reporting(E_ALL) ?>


<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle() ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/fontawesome-all.min.css'))
            ->prependStylesheet($this->basePath('css/lux.bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/app-script.js'))
            ->prependFile($this->basePath('js/fontawesome-all.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
            ->prependFile($this->basePath('js/jquery-3.2.1.min.js'))
        ?>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation" style="">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor03">
                <?php
                     echo $this->navigation('topNavigation')
                               ->menu()
                               ->setUlClass('navbar-nav mr-auto')
                               ->setPartial('partial/topmenu.phtml')
                               ->render();
                ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer class="footer">
            <hr>
            <div class="container">
                <p>&copy; <?= $this->getYear() ?> by PHP-User. All rights reserved.</p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>

        <a   id="back-to-top"
             href="#"
             role="button"
             data-toggle="tooltip"
             data-placement="left">
            <span style="font-size:3em; color:#919aa1;">
                <i class="far fa-arrow-alt-circle-up"></i>
            </span>
        </a>
    </body>
</html>
