<?php

/*class Greeting
{
    public function hello()
    {
        echo 'Hello world!' . '<hr>';
    }
}

class MyGreeting
{
    public $greeting;

    public function __construct(Greeting $greeting)
    {
        $this->greeting = $greeting;
    }
}

#$myGreeting = new MyGreeting(new Greeting());
#$myGreeting->greeting->hello();

$di = new Zend\Di\Di();
$myGreeting = $di->get('MyGreeting');
$myGreeting->greeting->hello();*/

?>

<?php
$headTitle = 'Training';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<p><?= $this->escapeHtml($this->greeting) ?></p>
